[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "4f2a7b8c9d1e3f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a"
email_password = "woam rxoy hcoj lkgb"
email_sender = "aj.30122003@gmail.com"

[auth.google]
client_id = "88657482887-s7nmsnnshem09svphpt9uc4e4bk49suf.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
